//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicMangement
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallTheRoll
    {
        public int id { get; set; }
        public int EmpeloyId { get; set; }
        public Nullable<System.TimeSpan> TimeIn { get; set; }
        public Nullable<System.TimeSpan> TimeOut { get; set; }
    
        public virtual Employes Employes { get; set; }
    }
}
