//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicMangement
{
    using System;
    using System.Collections.Generic;
    
    public partial class DarmanType
    {
        public DarmanType()
        {
            this.Insurance = new HashSet<Insurance>();
        }
    
        public int id { get; set; }
        public string DarmanName { get; set; }
    
        public virtual ICollection<Insurance> Insurance { get; set; }
    }
}
