//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicMangement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public Patient()
        {
            this.Visit = new HashSet<Visit>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string lname { get; set; }
        public string NCode { get; set; }
        public Nullable<int> InsuranceType { get; set; }
    
        public virtual ICollection<Visit> Visit { get; set; }
    }
}
