//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicMangement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visit
    {
        public int id { get; set; }
        public int EmployeId { get; set; }
        public int PatientId { get; set; }
        public int InsuranceId { get; set; }
        public string Prescription { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int Price { get; set; }
    
        public virtual Employes Employes { get; set; }
        public virtual Insurance Insurance { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
