//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic_Management_website.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemUser
    {
        public int id { get; set; }
        public string name { get; set; }
        public string lname { get; set; }
        public string UserName { get; set; }
        public string Passwor { get; set; }
        public Nullable<bool> Report { get; set; }
        public Nullable<bool> Search { get; set; }
        public Nullable<bool> Setting { get; set; }
        public Nullable<bool> Insert { get; set; }
    }
}
