//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicMangement
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployesType
    {
        public EmployesType()
        {
            this.Employes = new HashSet<Employes>();
        }
    
        public int id { get; set; }
        public string Ename { get; set; }
    
        public virtual ICollection<Employes> Employes { get; set; }
    }
}
