//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicMangement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insurance
    {
        public Insurance()
        {
            this.Visit = new HashSet<Visit>();
        }
    
        public int id { get; set; }
        public string IName { get; set; }
        public int Percentage { get; set; }
        public int darmanType { get; set; }
    
        public virtual DarmanType DarmanType1 { get; set; }
        public virtual ICollection<Visit> Visit { get; set; }
    }
}
