//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicMangement
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class ClinicMangementEntities2 : DbContext
    {
        public ClinicMangementEntities2()
            : base("name=ClinicMangementEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CallTheRoll> CallTheRoll { get; set; }
        public DbSet<DarmanType> DarmanType { get; set; }
        public DbSet<Employes> Employes { get; set; }
        public DbSet<EmployesType> EmployesType { get; set; }
        public DbSet<Insurance> Insurance { get; set; }
        public DbSet<Patient> Patient { get; set; }
        public DbSet<RootUser> RootUser { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<SystemUsers> SystemUsers { get; set; }
        public DbSet<Visit> Visit { get; set; }
    
        public virtual ObjectResult<FetchEmployes_Result> FetchEmployes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FetchEmployes_Result>("FetchEmployes");
        }
    
        public virtual ObjectResult<FetchInsurance_Result> FetchInsurance()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FetchInsurance_Result>("FetchInsurance");
        }
    }
}
